[project]
name = "shop-assist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hamza", email = "hamza140934@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.4.2",
    "langchain-core>=1.6.5",
    "langchain-google-genai>=4.4.0",
    "langgraph-checkpoint-postgres>=3.1.2",
    "psycopg[binary]>=3.3.6",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[project.scripts]
shop-assist = "shop_assist:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
